apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: rabbitmq
spec:
  containers:
    - args:
        - "9999999"
      command:
        - sleep
      image: europe-central2-docker.pkg.dev/cicd-383714/devops/swiss-army-knife:latest
      imagePullPolicy: Always
      name: swiss
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      securityContext:
        privileged: false
        runAsGroup: 1000
        runAsUser: 1000
      workingDir: /var/opt/swiss
  restartPolicy: Never
  serviceAccountName: default
