apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consumer-role-bind
  namespace: rabbitmq
subjects:
- kind: ServiceAccount
  name: consumer-secret-reader
roleRef:
  kind: Role
  name: consumer-role-secret
  apiGroup: rbac.authorization.k8s.io

